### ISSUE TITLE
Fetch an API & implement detail view

### ISSUE THREAD

**Issue by dllanob** [li5vany/frontend-test-master#1]
### 1. Try to fetch the job list Github API https://jobs.github.com/api with the information available from the request.

> **GET /positions.json**
> Search for jobs by term, location, full time vs part time, or any combination of the three. All parameters are optional.
> 
> **Parameters**
> 
> **description** — A search term, such as "ruby" or "java". This parameter is aliased to search.
> **location** — A city name, zip code, or other location search term.
> **lat** — A specific latitude. If used, you must also send long and must not send location.
> **long** — A specific longitude. If used, you must also send lat and must not send location.
> **full_time** — If you want to limit results to full time positions set this parameter to 'true'.

### 2.  Implement detail view with the following endpoint. (The UI specifications is all up to you - try to follow the same style guide) 

> **GET /positions/ID.json**
> Retrieve the JSON representation of a single job posting.
> 
> **Parameters**
> 
> **markdown** — Set to 'true' to get the description and how_to_apply fields as Markdown.

**Comment by li5vany** [comment]
https://github.com/li5vany/frontend-test-master/tree/feature/FTM-FetchJobs
